### ISSUE TITLE
sella does not work with `jax>=0.4.25`

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [zadorlab/sella#35]
Do `pip install sella` in a fresh environment to get the most recent version of `jax` (0.4.25) and then do `import sella`. You'll get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/sella/__init__.py", line 3, in <module>
    from jax.config import config
ImportError: cannot import name 'config' from 'jax.config' (/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/jax/config.py)
```
